name = "rolldorado-app-de"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=rolldorado-app.de"
HMAC_KEY = "534c96791c9fc9931eaedb1161b693c8733a782fbcd2c2738e8ce6f4b058f596"
COOKIE_NAME = "dod"
PLAY_PATH = "launch"
BUTTON_ID = "p9f730ea2289c3f595323e139585a9255"
GATE_SALT = "cf75b12a15ce3799"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "oj4i"
CTA_SELECTOR = ".play-button"
